// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optica.Api.Datos;

#nullable disable

namespace Optica.Api.Datos.Migraciones
{
    [DbContext(typeof(OpticaDbContext))]
    [Migration("20261005201412_Configuracion")]
    partial class Configuracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Optica.Api.Acceso.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Acceso", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acceso_Unico", "Id = 1");
                        });
                });

            modelBuilder.Entity("Optica.Api.Configuracion.ParametrosNegocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionFiscal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MultiploRedondeo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopeIdentificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Configuracion_Unica", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlicuotaIva = 21m,
                            CondicionFiscal = "ResponsableInscripto",
                            MultiploRedondeo = 0.01m,
                            TopeIdentificacion = 10000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
