// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optica.Api.Datos;

#nullable disable

namespace Optica.Api.Datos.Migraciones
{
    [DbContext(typeof(OpticaDbContext))]
    [Migration("20261005204601_LineasPresupuesto")]
    partial class LineasPresupuesto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Optica.Api.Acceso.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Acceso", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acceso_Unico", "Id = 1");
                        });
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Articulo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MargenUtilidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoBusqueda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoProveedor");

                    b.HasIndex("Descripcion");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Optica.Api.Configuracion.ParametrosNegocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionFiscal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MultiploRedondeo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopeIdentificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Configuracion_Unica", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlicuotaIva = 21m,
                            CondicionFiscal = "ResponsableInscripto",
                            MultiploRedondeo = 0.01m,
                            TopeIdentificacion = 10000000m
                        });
                });

            modelBuilder.Entity("Optica.Api.Presupuestos.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("Optica.Api.Presupuestos.Presupuesto", b =>
                {
                    b.OwnsOne("Optica.Api.Presupuestos.Cliente", "Cliente", b1 =>
                        {
                            b1.Property<int>("PresupuestoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApellidoBusqueda")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Dni")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Domicilio")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("NombreBusqueda")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");

                            b1.HasKey("PresupuestoId");

                            b1.HasIndex("ApellidoBusqueda");

                            b1.HasIndex("Dni");

                            b1.ToTable("Presupuestos");

                            b1.WithOwner()
                                .HasForeignKey("PresupuestoId");
                        });

                    b.OwnsMany("Optica.Api.Presupuestos.LineaPresupuesto", "Lineas", b1 =>
                        {
                            b1.Property<int>("PresupuestoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Orden")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Cantidad")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CodigoArticulo")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("PorcentajeDescuento")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("PrecioConDescuento")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("PrecioFinal")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("TEXT");

                            b1.HasKey("PresupuestoId", "Orden");

                            b1.ToTable("LineasPresupuesto", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PresupuestoId");
                        });

                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
